/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/base/Container/aside.vue')['default']
    Container: typeof import('./src/components/base/Container/container.vue')['default']
    Footer: typeof import('./src/components/base/Container/footer.vue')['default']
    Header: typeof import('./src/components/base/Container/header.vue')['default']
    Main: typeof import('./src/components/base/Container/main.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
